In [1]:
import numpy as np

In [10]:
vector_row = np.array([1, 2, 3])

In [3]:
vector_row

array([1, 2, 3])

In [4]:
vector_column = np.array([[1],
                          [2],
                          [3]])

In [5]:
vector_column

array([[1],
       [2],
       [3]])

In [11]:
vector_row.T

array([1, 2, 3])

In [9]:
vector_column.T

array([[1, 2, 3]])

In [16]:
a = np.array([[40, 10], [50, 11]])
a

array([[40, 10],
       [50, 11]])

In [17]:
a.mean(axis=1)     # to take the mean of each row

array([25. , 30.5])

In [18]:
a.mean(axis=0)     # to take the mean of each column

array([45. , 10.5])

In [19]:
np.mean(a, axis=1)

array([25. , 30.5])