In [1]:
# import the numpy pacage
import numpy as np

In [2]:
l = [123,456,789]

In [3]:
type(l)

list

In [4]:
# converting a list to numpy array
a = np.array(l)

In [5]:
a

array([123, 456, 789])

In [6]:
type(a)

numpy.ndarray

In [7]:
# explicit array creation
b = np.array([1,2,3,4,5,6,7,8])

In [8]:
b


array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
type(b)

numpy.ndarray

In [10]:
b.min()

1

In [11]:
b.mean()

4.5

In [12]:
b[0]

1

In [13]:
len(b)

8

In [17]:
np.append(b,55)

array([ 1,  2,  3,  4,  5,  6,  7,  8, 55])

In [18]:
c = np.array([10,20,55.5,22.9])

In [19]:
c

array([10. , 20. , 55.5, 22.9])

In [23]:
d = np.array([1,2,3,4,True,False])

In [24]:
d

array([1, 2, 3, 4, 1, 0])

In [25]:
e = np.array([1,2.9,3.5,4,True,False])

In [26]:
e

array([1. , 2.9, 3.5, 4. , 1. , 0. ])

In [28]:
e.mean()

2.066666666666667

In [29]:
# ---------------- Slicing of Numpy Arrays ---------------

In [30]:
# Behaviour of list slicing

In [31]:
mylist = [1,2,3,4,5]

In [32]:
# slicelist is a new list created
slicelist = mylist[:]

In [33]:
slicelist

[1, 2, 3, 4, 5]

In [34]:
mylist

[1, 2, 3, 4, 5]

In [36]:
# changes will not reflect to the original list mylist
slicelist[2]= 55

In [37]:
# changed in the slice 
slicelist

[1, 2, 55, 4, 5]

In [38]:
# unchanged in the original copy
mylist

[1, 2, 3, 4, 5]

-----

In [59]:
# original array
myArray = np.array([10,20,30,40,50])

In [60]:
# sliced array is like a view pointing to the original array not occupying actual space or creating a new copy
sliceA = myArray[:]

In [61]:
 myArray

array([10, 20, 30, 40, 50])

In [62]:
sliceA

array([10, 20, 30, 40, 50])

In [63]:
# lets make changes to the slice
sliceA[2] = 55

In [64]:
sliceA

array([10, 20, 55, 40, 50])

In [65]:
myArray

array([10, 20, 55, 40, 50])

In [66]:
myArray[0]=99

In [67]:
sliceA

array([99, 20, 55, 40, 50])

In [68]:
# making an actual copy of the array
copyA = myArray.copy()

In [69]:
copyA

array([99, 20, 55, 40, 50])

In [70]:
copyA[:]=0

In [71]:
copyA

array([0, 0, 0, 0, 0])

In [72]:
myArray

array([99, 20, 55, 40, 50])