In [1]:
import numpy as np

In [2]:
# creates a numpy array
mydata = np.arange(0,20)

In [3]:
type(mydata)

numpy.ndarray

In [4]:
mydata

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
print(mydata)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [6]:
# row by row population as default order = 'C'
Matx1 = np.reshape(mydata,(5,4))  

In [7]:
Matx1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [7]:
Matx1.shape

(5, 4)

In [ ]:
# as mydata is object of numpy array
# col by col population  as order = 'F'
Matx2 = mydata.reshape((5,4),order='F')  

In [9]:
Matx2

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [10]:
Matx2[0,2]

10

In [11]:
Matx1[2,2]

10

-----

In [13]:
# creating 3 regular list

r1 = ["I","am","happy"]
r2 = ["what","a","day"]
r3 = [1,2,3]

In [14]:
# all 3 list put together in other list

[r1,r2,r3]

[['I', 'am', 'happy'], ['what', 'a', 'day'], [1, 2, 3]]

In [15]:
# creating a matrix out of all lists using np.array

Matx3 = np.array([r1,r2,r3])

In [16]:
Matx3    # dtype =< U5     data is less than "U5" unicode 5 

array([['I', 'am', 'happy'],
       ['what', 'a', 'day'],
       ['1', '2', '3']], dtype='<U5')

In [17]:
# all gets converted to string as Matrix can hold single datatype
print(Matx3)

[['I' 'am' 'happy']
 ['what' 'a' 'day']
 ['1' '2' '3']]


# Operation on Matrix

In [8]:
list1 = np.arange(0,20)

In [9]:
list1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
m1 = np.reshape(list1,(5,4))

In [11]:
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [12]:
m2 = np.reshape(list1,(5,4),order = 'F')

In [13]:
m2

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [14]:
m1+m2

array([[ 0,  6, 12, 18],
       [ 5, 11, 17, 23],
       [10, 16, 22, 28],
       [15, 21, 27, 33],
       [20, 26, 32, 38]])

In [15]:
m1-m2

array([[  0,  -4,  -8, -12],
       [  3,  -1,  -5,  -9],
       [  6,   2,  -2,  -6],
       [  9,   5,   1,  -3],
       [ 12,   8,   4,   0]])

In [16]:
m1*m2

array([[  0,   5,  20,  45],
       [  4,  30,  66, 112],
       [ 16,  63, 120, 187],
       [ 36, 104, 182, 270],
       [ 64, 153, 252, 361]])

In [17]:
m1/m2

C:\Users\Bibhu\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[       nan, 0.2       , 0.2       , 0.2       ],
       [4.        , 0.83333333, 0.54545455, 0.4375    ],
       [4.        , 1.28571429, 0.83333333, 0.64705882],
       [4.        , 1.625     , 1.07692308, 0.83333333],
       [4.        , 1.88888889, 1.28571429, 1.        ]])

In [22]:
np.matrix.round(m1/m2)

C:\Users\Bibhu\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan,  0.,  0.,  0.],
       [ 4.,  1.,  1.,  0.],
       [ 4.,  1.,  1.,  1.],
       [ 4.,  2.,  1.,  1.],
       [ 4.,  2.,  1.,  1.]])

In [18]:
np.nan_to_num(m1/m2)

C:\Users\Bibhu\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[0.        , 0.2       , 0.2       , 0.2       ],
       [4.        , 0.83333333, 0.54545455, 0.4375    ],
       [4.        , 1.28571429, 0.83333333, 0.64705882],
       [4.        , 1.625     , 1.07692308, 0.83333333],
       [4.        , 1.88888889, 1.28571429, 1.        ]])